version: '3.1'

services:
  postgres:
    image: postgres
    container_name: delivery-app-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres