server:
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/development
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    operations-sorter: method
    path: /
    doc-expansion: none

env:
  secrets:
    jwt-token: xxx
